# Resolve react_native_pods.rb with node to allow for hoisting
use_frameworks! :linkage => :static

pod 'FirebaseCore', '11.12.0'
pod 'FirebaseAuth', '11.12.0'
pod 'FirebaseStorage', '11.12.0'
pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true

require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => :static
end

target 'bhogi' do
  config = use_native_modules!
  pod 'GoogleMaps'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

    permissions_path = '../node_modules/react-native-permissions/ios'

    # Check if the new structure exists, otherwise use the old one
    if File.exist?("#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec")
      pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
    elsif File.exist?("#{permissions_path}/LocationWhenInUse.podspec")
      pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
    else
      # For newer versions that might use a different structure
      pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
    end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
